name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Define the build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  # Define the SonarQube analysis job
  sonar_analysis:
    needs: build  # Ensure build job completes first
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Required for SonarQube analysis

      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Set your SonarQube token in secrets
        run: |
          sonar-scanner \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarqube.yourdomain.com \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
